import { MigrationInterface, QueryRunner } from 'typeorm';

// SPEC §4. Written by hand as raw SQL: the triggers are the heart of change capture and must be
// readable exactly as Postgres runs them (SPEC §5.6 rule 3).
export class InitialSchema1727164800000 implements MigrationInterface {
  name = 'InitialSchema1727164800000';

  async up(q: QueryRunner): Promise<void> {
    // --- Source (SPEC §4.1) -------------------------------------------------------------
    await q.query(`
      CREATE TABLE customers (
        id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        email       TEXT          NOT NULL,
        name        TEXT          NOT NULL,
        city        TEXT          NOT NULL,
        segment     TEXT          NOT NULL,
        balance     NUMERIC(12,2) NOT NULL DEFAULT 0,
        attributes  JSONB         NOT NULL DEFAULT '{}'::jsonb,
        version     BIGINT        NOT NULL DEFAULT 1,
        updated_at  TIMESTAMPTZ   NOT NULL DEFAULT now()
      )`);

    // Every UPDATE bumps the version, whatever the writer sets: the version is what the sinks
    // use to reject stale writes (SPEC §5.5), so no writer may be able to forget it.
    await q.query(`
      CREATE FUNCTION customers_bump_version() RETURNS trigger LANGUAGE plpgsql AS $$
      BEGIN
        NEW.version    := OLD.version + 1;
        NEW.updated_at := now();
        RETURN NEW;
      END $$`);
    await q.query(`
      CREATE TRIGGER customers_bump_version
        BEFORE UPDATE ON customers
        FOR EACH ROW EXECUTE FUNCTION customers_bump_version()`);

    // --- Outbox (SPEC §4.2) -------------------------------------------------------------
    await q.query(`
      CREATE TABLE customer_changes (
        seq          BIGSERIAL   PRIMARY KEY,
        customer_id  BIGINT      NOT NULL,
        op           TEXT        NOT NULL CHECK (op IN ('upsert', 'delete')),
        version      BIGINT      NOT NULL,
        created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
      )`);

    // Runs in the same transaction as the change: the change and its outbox row commit or
    // roll back together. A delete gets OLD.version + 1 so it always outranks the last upsert.
    await q.query(`
      CREATE FUNCTION customers_to_outbox() RETURNS trigger LANGUAGE plpgsql AS $$
      BEGIN
        IF TG_OP = 'DELETE' THEN
          INSERT INTO customer_changes (customer_id, op, version) VALUES (OLD.id, 'delete', OLD.version + 1);
          RETURN OLD;
        END IF;
        INSERT INTO customer_changes (customer_id, op, version) VALUES (NEW.id, 'upsert', NEW.version);
        RETURN NEW;
      END $$`);
    await q.query(`
      CREATE TRIGGER customers_to_outbox
        AFTER INSERT OR UPDATE OR DELETE ON customers
        FOR EACH ROW EXECUTE FUNCTION customers_to_outbox()`);

    // --- Pipeline state (SPEC §4.3, §4.6, §4.7) ----------------------------------------
    await q.query(`
      CREATE TABLE pipeline_checkpoints (
        stream        TEXT        PRIMARY KEY CHECK (stream IN ('backfill', 'incremental')),
        position      BIGINT      NOT NULL DEFAULT 0,
        completed_at  TIMESTAMPTZ,
        updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
      )`);
    await q.query(`INSERT INTO pipeline_checkpoints (stream) VALUES ('backfill'), ('incremental')`);

    await q.query(`
      CREATE TABLE pipeline_control (
        id                 SMALLINT    PRIMARY KEY DEFAULT 1 CHECK (id = 1),
        backfill_state     TEXT        NOT NULL DEFAULT 'running' CHECK (backfill_state IN ('running', 'paused')),
        incremental_state  TEXT        NOT NULL DEFAULT 'running' CHECK (incremental_state IN ('running', 'paused')),
        batch_size         INT         NOT NULL DEFAULT 500 CHECK (batch_size BETWEEN 1 AND 10000),
        poll_interval_ms   INT         NOT NULL DEFAULT 1000 CHECK (poll_interval_ms >= 100),
        updated_at         TIMESTAMPTZ NOT NULL DEFAULT now()
      )`);
    await q.query(`INSERT INTO pipeline_control DEFAULT VALUES`);

    await q.query(`
      CREATE TABLE pipeline_heartbeat (
        instance_id       TEXT             PRIMARY KEY,
        started_at        TIMESTAMPTZ      NOT NULL,
        last_beat_at      TIMESTAMPTZ      NOT NULL,
        backfill_rate     DOUBLE PRECISION NOT NULL DEFAULT 0,
        incremental_rate  DOUBLE PRECISION NOT NULL DEFAULT 0
      )`);

    // --- DLQ (SPEC §4.4) ----------------------------------------------------------------
    await q.query(`
      CREATE TABLE dlq_records (
        id               BIGSERIAL   PRIMARY KEY,
        sink             TEXT        NOT NULL CHECK (sink IN ('es', 'stream')),
        customer_id      BIGINT      NOT NULL,
        version          BIGINT      NOT NULL,
        payload          JSONB       NOT NULL,
        error_type       TEXT        NOT NULL,
        error_reason     TEXT        NOT NULL,
        stream           TEXT        NOT NULL CHECK (stream IN ('backfill', 'incremental')),
        batch_id         TEXT        NOT NULL,
        batch_position   INT         NOT NULL,
        attempts         INT         NOT NULL DEFAULT 1,
        status           TEXT        NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'replayed', 'failed')),
        created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
        last_attempt_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
        -- A batch replayed after a crash must not record the same failure twice.
        UNIQUE (sink, customer_id, version)
      )`);
    await q.query(`CREATE INDEX dlq_records_pending ON dlq_records (sink) WHERE status = 'pending'`);
  }

  async down(q: QueryRunner): Promise<void> {
    await q.query(`DROP TABLE dlq_records, pipeline_heartbeat, pipeline_control, pipeline_checkpoints`);
    await q.query(`DROP TRIGGER customers_to_outbox ON customers`);
    await q.query(`DROP TRIGGER customers_bump_version ON customers`);
    await q.query(`DROP FUNCTION customers_to_outbox(), customers_bump_version()`);
    await q.query(`DROP TABLE customer_changes, customers`);
  }
}
